networks:
  portfolio_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: portfolio_postgres_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-devuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devsecret}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_dev}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - portfolio_network_dev
    restart: unless-stopped

  redis_cache:
    image: redis:7-alpine
    container_name: portfolio_redis_dev
    ports:
      - '6379:6379'
    networks:
      - portfolio_network_dev
    restart: unless-stopped
