name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest
          no-cache: true

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest
          no-cache: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to k3s
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          port: ${{ secrets.K3S_PORT }}
          script: |
            # Remove old images to force fresh pull
            sudo k3s crictl rmi ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend:latest || true
            sudo k3s crictl rmi ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest || true
            
            # Force rollout restart which will pull fresh images due to imagePullPolicy: Always
            sudo k3s kubectl rollout restart deployment/backend -n portfolio
            sudo k3s kubectl rollout restart deployment/frontend -n portfolio
            
            # Wait for rollout to complete
            sudo k3s kubectl rollout status deployment/backend -n portfolio
            sudo k3s kubectl rollout status deployment/frontend -n portfolio
            
            # Update DNS IPs for the new pods
            sudo k3s kubectl delete job dns-ip-updater -n portfolio --ignore-not-found=true
            sudo k3s kubectl apply -f /home/steven/k8s-projects/portfolio/manifests/12-dns-update-job.yaml
            
            # Wait for DNS update to complete
            sudo k3s kubectl wait --for=condition=complete job/dns-ip-updater -n portfolio --timeout=120s || true